#!/bin/bash

scp target/dependency/guava-24.0-jre.jar target/dependency/dagger-2.15.jar target/dependency/javax.inject-1.jar target/robot-prototype-1.0-SNAPSHOT.jar target/dependency/pi4j-core-1.2-SNAPSHOT.jar "pi@raspberrypi:/home/pi/Documents/Java\ Tests"
