#!/bin/bash

if ssh -lpi raspberrypi '[ -e robot-prototype/service/remove-service ]'
then
   ssh -lpi raspberrypi 'sudo robot-prototype/service/remove-service && rm -rf robot-prototype/*'
fi

scp target/robot-prototype-1.0-SNAPSHOT-bin.tar.gz "pi@raspberrypi:robot-prototype"
ssh -lpi raspberrypi 'tar -C robot-prototype -xzvf robot-prototype/robot-prototype-1.0-SNAPSHOT-bin.tar.gz && sudo robot-prototype/service/install-service'


