[pi]
clockDivisor = 2
pwmMode = "PWM_MODE_MS"

[joystick]
axes = [1, 4]

[motor]
pwmPeriod = 1024

   [[motor.instance]]
   index = 0
   name = "left"
   enablePin = 24
   directionPin = 23
   invert = true
   minPwm = 0.33

   [[motor.instance]]
   index = 1
   name = "right"
   enablePin = 26
   directionPin = 27
   invert = false
   minPwm = 0.33

[selector]
   defaultController = "manualController"
   buttonControllerMap = { 0 = "manualController" }

[manualController]
axisMotorMap = { 1 = 0, 4 = 1 }

[rangeFinder]
pollPeriod = 150

   [rangeFinder.us100Configuration]
   serialDevicePath = "/dev/serial0"
   baud = 9600
   dataBits = 8
   parity = "NONE"
   stopBits = 1
   flowControl = "NONE"