[pi]
clockDivisor = 2
pwmMode = "PWM_MODE_MS"

[joystick]
axes = [1, 5]

[motor]
pwmPeriod = 1024

   [[motor.instance]]
   index = 0
   name = "left"
   enablePin = 24
   directionPin = 23
   invert = true
   minPwm = 0.33

   [[motor.instance]]
   index = 1
   name = "right"
   enablePin = 26
   directionPin = 27
   invert = false
   minPwm = 0.33

[controller]
axisMotorMap = { 1 = 0, 5 = 1 }